version: "3"

services:
  app:
    build:
      context: ./app/
      args:
        test_arg: hello,world!
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=qpa
      - POSTGRES_PASSWORD=qpafinalproject
      - POSTGRES_DB=genomic_db
